spring:
  application:
    name: transaction-service
  datasource:
    url: jdbc:postgresql://localhost:5434/${TRANSACTION_DATABASE_NAME:transaction-db}
    username: ${TRANSACTION_DATABASE_USER:transaction-admin}
    password: ${TRANSACTION_DATABASE_PASSWORD:transaction-password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
  config:
    import: optional:file:../../../docker/.env[.properties] # TODO: import data from .env file
  kafka:
    bootstrap-servers: localhost:9092

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-type: TIME_BASED  # Окно на основе времени (10 секунд)
        sliding-window-size: 10          # Размер окна - 10 секунд
        minimum-number-of-calls: 5       # Нужно минимум 5 вызовов для анализа
        failure-rate-threshold: 50       # 50%
        wait-duration-in-open-state: 60s # 60 секунд в OPEN состоянии
        permitted-number-of-calls-in-half-open-state: 3 # 3 тестовых вызова
        record-exceptions: # какие исключения считать сбоями
          - java.io.IOException           # Сетевые ошибки
          - java.util.concurrent.TimeoutException # Таймауты
        ignore-exceptions:
          - ru.mirea.newrav1k.transactionservice.exception.TransactionServiceException
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 100ms
        retry-exceptions:
          - org.springframework.orm.ObjectOptimisticLockingFailureException
        ignore-exceptions:
          - ru.mirea.newrav1k.transactionservice.exception.TransactionServiceException

transaction-service:
  services:
    account-service:
      base-url: http://localhost:8082
  kafka:
    topics:
      # Исходящие события
      transaction-successfully-created: transaction.transaction.successfully.created.v1
      transaction-balance-failure: transaction.transaction.balance.failure.v1
      transaction-compensate: transaction.transaction.compensate.v1
      transaction-compensate-failure: transaction.transaction.compensate.failure.v1
      transaction-compensate-difference-amount: transaction.transaction.compensate.difference.amount.v1

    group-id: ${spring.application.name}

logging:
  level:
    ru.mirea.newrav1k.transactionservice: debug

server:
  port: 8083