spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service-oauth2-authentication
              uri: http://localhost:8081
              predicates:
                - Path=/oauth2/**
            - id: user-service-authentication
              uri: http://localhost:8081
              predicates:
                - Path=/api/auth/**
            - id: user-service-trackers
              uri: http://localhost:8081
              predicates:
                - Path=/api/trackers/**
            - id: account-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/accounts/**
              filters:
                - JwtAuthenticationFilter
            - id: transaction-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/transactions/**
              filters:
                - JwtAuthenticationFilter
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/api/auth/.well-known/jwks.json

server:
  port: 8080