spring:
  application:
    name: user-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/api/auth/.well-known/jwks.json
  datasource:
    url: jdbc:postgresql://localhost:5432/${USER_DATABASE_NAME:user-db}
    username: ${USER_DATABASE_USER:user-admin}
    password: ${USER_DATABASE_PASSWORD:user-password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
  config:
    import: optional:file:../../../docker/.env[.properties] # TODO: import data from .env file

user-service:
  jwt:
    access-token:
      expiry: 30m
    refresh-token:
      expiry: 15d
    private-key-path: keys/private_pkcs8.pem
    public-key-path: keys/public.pem

logging:
  level:
    org.springframework.security: trace

server:
  port: 8081