spring:
  application:
    name: category-service
  datasource:
    url: jdbc:postgresql://localhost:5435/${CATEGORY_DATABASE_NAME:category-db}
    username: ${CATEGORY_DATABASE_USER:category-admin}
    password: ${CATEGORY_DATABASE_PASSWORD:category-password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
  kafka:
    bootstrap-servers: localhost:9092
category-service:
  kafka:
    topics:
      category-delete: category.category.deleted.v1


    group-id: ${spring.application.name}


server:
  port: 8084
logging:
  level:
    ru.mirea.nisanchik.categoryservice: debug