spring:
  application:
    name: account-service
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:tracker-database}
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
  config:
    import: optional:file:../../../.env # TODO: import data from .env file

resilience4j:
  retry:
    configs:
      optimisticLockingConfig:
        max-attempts: 3
        wait-duration: 100ms
        retry-exceptions:
          - org.springframework.orm.ObjectOptimisticLockingFailureException
        ignore-exceptions:
          - ru.mirea.newrav1k.accountservice.exception.AccountNotFoundException
    instances:
      accountService:
        base-config: optimisticLockingConfig

server:
  port: 8083