spring:
  application:
    name: account-service
  datasource:
    url: jdbc:postgresql://localhost:5433/${ACCOUNT_DATABASE_NAME:account-db}
    username: ${ACCOUNT_DATABASE_USER:account-admin}
    password: ${ACCOUNT_DATABASE_PASSWORD:account-password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
  config:
    import: optional:file:../../../docker/.env[.properties] # TODO: import data from .env file

resilience4j:
  retry:
    configs:
      optimisticLockingConfig:
        max-attempts: 5
        wait-duration: 100ms
        retry-exceptions:
          - org.springframework.dao.OptimisticLockingFailureException
          - jakarta.persistence.OptimisticLockException
        ignore-exceptions:
          - ru.mirea.newrav1k.accountservice.exception.AccountServiceException
    instances:
      accountService:
        base-config: optimisticLockingConfig

server:
  port: 8082